CREATE OR REPLACE TABLE WEATHER.STAGING.REQUESTS AS
SELECT A.RECORD_ID || '_' || B.CITY_ID AS REQUEST_ID,
    A.RECORD_ID,
    B.CITY_ID,
    A.REQUEST_STATUS
FROM WEATHER.RAW.RECORDS A
    LEFT JOIN WEATHER.STAGING.CITIES B USING(CITY_RAW)