CREATE TABLE IF NOT EXISTS WEATHER.STAGING.SUMMARY AS
SELECT CITY,
    MIN(HUMIDITY) AS HUMIDITY_MIN,
    AVG(HUMIDITY) AS HUMIDITY_AVG,
    MAX(HUMIDITY) AS HUMIDITY_MAX,
    MIN(TEMPERATURE) AS TEMPERATURE_MIN,
    AVG(TEMPERATURE) AS TEMPERATURE_AVG,
    MAX(TEMPERATURE) AS TEMPERATURE_MAX,
    MAX(UPDATED_AT) AS LAST_TIME_UPDATED,
    CURRENT_TIMESTAMP AS UPDATED_AT
FROM WEATHER.STAGING.HOURLY
GROUP BY 1
ORDER BY 1 DESC
LIMIT 0;
INSERT INTO WEATHER.STAGING.SUMMARY
SELECT CITY,
    MIN(HUMIDITY) AS HUMIDITY_MIN,
    AVG(HUMIDITY) AS HUMIDITY_AVG,
    MAX(HUMIDITY) AS HUMIDITY_MAX,
    MIN(TEMPERATURE) AS TEMPERATURE_MIN,
    AVG(TEMPERATURE) AS TEMPERATURE_AVG,
    MAX(TEMPERATURE) AS TEMPERATURE_MAX,
    MAX(UPDATED_AT) AS LAST_TIME_UPDATED,
    CURRENT_TIMESTAMP AS UPDATED_AT
FROM WEATHER.STAGING.HOURLY
GROUP BY 1
ORDER BY 1 DESC;